llm_model:
  num_ctx: 4096
  temperature: 0.3

small_llm_model:
  model: "gemma3:4b-it-q4_K_M"
  temperature: 1

retriever:
  topk: 10

reranker:
  model: "ms-marco-MultiBERT-L-12"
  topk: 5
  score_threshold: 0.5
